"""
python/tara_core/security/containment.py

Immediate Containment Engine for TARA Security Architecture.
When suspicious behavior reaches quarantine/restriction threshold:
1. Halts job assignment
2. Revokes capabilities
3. Revokes/restricts sessions
4. Isolates network access
5. Blocks creator/protected endpoints and secrets
6. Cancels unsafe pending operations
7. Quarantines untrusted outputs while preserving verified results
"""

import time
import logging
from typing import Dict, List, Optional, Any, Set
from dataclasses import dataclass, field

from tara_core.security.security_state import (
    SecurityState,
    TrustBoundary,
    CapabilityProfile,
    SecurityContext
)

logger = logging.getLogger("tara_core.security.containment")


@dataclass
class QuarantinedOutput:
    output_id: str
    producer_id: str
    boundary: TrustBoundary
    payload: Any
    reason: str
    quarantined_at: float = field(default_factory=time.time)
    status: str = "QUARANTINED"  # "QUARANTINED", "DISCARDED", "CLEARED"


class ContainmentManager:
    """
    Enforces immediate containment and isolation on compromised components.
    """

    def __init__(self):
        self._quarantined_outputs: Dict[str, QuarantinedOutput] = {}
        self._revoked_sessions: Set[str] = set()
        self._isolated_workers: Set[str] = set()
        self._audit_events: List[Dict[str, Any]] = []

    def contain_entity(self, context: SecurityContext, reason: str) -> Dict[str, Any]:
        """
        Executes complete immediate containment on an entity reaching QUARANTINED or RESTRICTED.
        """
        context.state = SecurityState.QUARANTINED
        context.quarantine_reason = reason
        context.last_updated = time.time()

        # 1. Revoke all active capabilities
        context.capabilities = CapabilityProfile(
            inference=False,
            filesystem="none",
            network="none",
            current_user_memory=False,
            other_user_memory=False,
            creator_api=False,
            model_write=False,
            security_policy_write=False,
            provider_secret_access=False,
            worker_control=False
        )

        # 2. Mark worker as isolated
        if context.boundary == TrustBoundary.WORKER:
            self._isolated_workers.add(context.entity_id)

        # 3. Revoke sessions associated with entity
        self._revoked_sessions.add(context.entity_id)

        # 4. Record containment event
        containment_record = {
            "timestamp": time.time(),
            "entity_id": context.entity_id,
            "boundary": context.boundary.value,
            "action": "IMMEDIATE_CONTAINMENT",
            "reason": reason,
            "capabilities_revoked": True,
            "network_isolated": True,
            "sessions_revoked": True
        }
        self._audit_events.append(containment_record)
        logger.warning(f"CONTAINMENT ENFORCED on {context.boundary.value} '{context.entity_id}': {reason}")
        return containment_record

    def quarantine_output(
        self,
        output_id: str,
        producer_id: str,
        boundary: TrustBoundary,
        payload: Any,
        reason: str
    ) -> QuarantinedOutput:
        """Quarantines untrusted output generated by a suspicious/quarantined component."""
        qo = QuarantinedOutput(
            output_id=output_id,
            producer_id=producer_id,
            boundary=boundary,
            payload=payload,
            reason=reason
        )
        self._quarantined_outputs[output_id] = qo
        logger.info(f"Untrusted output '{output_id}' from '{producer_id}' placed in QUARANTINE: {reason}")
        return qo

    def is_session_revoked(self, session_or_entity_id: str) -> bool:
        return session_or_entity_id in self._revoked_sessions

    def is_worker_isolated(self, worker_id: str) -> bool:
        return worker_id in self._isolated_workers

    def list_quarantined_outputs(self) -> List[Dict[str, Any]]:
        return [
            {
                "output_id": qo.output_id,
                "producer_id": qo.producer_id,
                "reason": qo.reason,
                "status": qo.status,
                "quarantined_at": qo.quarantined_at
            }
            for qo in self._quarantined_outputs.values()
        ]
