/**
 * Cloudflare Worker: TARA Public Edge & Gateway
 * Worker Name: tara
 *
 * Responsibilities:
 * - Public HTTPS entry point for TARA AI Core
 * - Edge routing to TARA live production backend (Hugging Face Space container)
 * - Zero mock responses. Real end-to-end inference routing.
 */

const CANONICAL_MODEL_IDENTITY = "TARA";
const CANONICAL_MODEL_SHA256 = "7a50308b799f2654baeafbd64dec31f088c3b07b446e198cd0f9ec2b7c0af309";
const CANONICAL_PARAM_COUNT = 118080;
const DEFAULT_BACKEND_URL = "https://manjukp6-tara.hf.space";

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-API-Key, X-Tara-Session-Token",
};

export default {
  async fetch(request, env, ctx) {
    if (request.method === "OPTIONS") {
      return new Response(null, { headers: CORS_HEADERS });
    }

    const url = new URL(request.url);
    const path = url.pathname;
    const backendUrl = env.TARA_CONTROL_PLANE_URL || DEFAULT_BACKEND_URL;

    try {
      // 1. Root & Chat UI
      if (path === "/" || path === "/chat") {
        return handleChatUI(env);
      }

      // 2. Health & Status Endpoints
      if (path === "/health" || path === "/api/v1/health") {
        return forwardToBackend(request, backendUrl, "/health");
      }

      if (path === "/api/v1/control_plane/status") {
        return jsonResponse({
          status: "HEALTHY",
          control_plane: "TARA Dynamic Compute Edge Gateway",
          version: "2.1.0",
          backend_url: backendUrl,
          canonical_model_sha256: CANONICAL_MODEL_SHA256,
          canonical_param_count: CANONICAL_PARAM_COUNT,
          deployment_type: "SERVERLESS_EDGE",
          provider: "cloudflare",
          timestamp: Date.now() / 1000
        });
      }

      // 3. Chat & Inference Endpoints
      if (path === "/v1/chat" || path === "/api/v1/chat") {
        if (request.method !== "POST") {
          return errorResponse("Method not allowed", 405);
        }
        return forwardToBackend(request, backendUrl, "/v1/chat");
      }

      if (path === "/api/v1/inference") {
        if (request.method !== "POST") {
          return errorResponse("Method not allowed", 405);
        }
        return forwardToBackend(request, backendUrl, "/api/v1/inference");
      }

      // 4. Fallback proxy for any other /api/v1/ routes
      if (path.startsWith("/api/v1/")) {
        return forwardToBackend(request, backendUrl, path);
      }

      return errorResponse("Not Found", 404);
    } catch (err) {
      return errorResponse(`Edge Gateway Error: ${err.message}`, 502);
    }
  }
};

async function forwardToBackend(request, backendUrl, targetPath) {
  const base = backendUrl.replace(/\/+$/, "");
  const target = `${base}${targetPath}`;
  try {
    const backendReq = new Request(target, {
      method: request.method,
      headers: {
        "Content-Type": request.headers.get("Content-Type") || "application/json",
        "Accept": "application/json"
      },
      body: request.method !== "GET" && request.method !== "HEAD" ? await request.text() : undefined
    });

    const res = await fetch(backendReq);
    const data = await res.text();

    return new Response(data, {
      status: res.status,
      headers: {
        "Content-Type": res.headers.get("Content-Type") || "application/json",
        ...CORS_HEADERS
      }
    });
  } catch (e) {
    return jsonResponse({
      status: "ERROR",
      error: `Failed to communicate with TARA production backend: ${e.message}`,
      target_url: target
    }, 502);
  }
}

// Embedded canonical clean Chat UI
const CANONICAL_FRONTEND_B64 = "PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0iVVRGLTgiPgogIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wLCBtYXhpbXVtLXNjYWxlPTEuMCwgdXNlci1zY2FsYWJsZT1ubywgdmlld3BvcnQtZml0PWNvdmVyIj4KICA8dGl0bGU+VEFSQTwvdGl0bGU+CiAgPHN0eWxlPgogICAgOnJvb3QgewogICAgICAtLWJnOiAjMGIwZjE5OwogICAgICAtLWNhcmQtYmc6ICMxMTE4Mjc7CiAgICAgIC0tYnViYmxlLXVzZXI6ICMyNTYzZWI7CiAgICAgIC0tYnViYmxlLXRhcmE6ICMxZTI5M2I7CiAgICAgIC0tdGV4dDogI2Y5ZmFmYjsKICAgICAgLS10ZXh0LW11dGVkOiAjOWNhM2FmOwogICAgICAtLWFjY2VudDogIzM4YmRmODsKICAgICAgLS1hY2NlbnQtZ2xvdzogcmdiYSg1NiwgMTg5LCAyNDgsIDAuMjUpOwogICAgICAtLWJvcmRlcjogIzFmMjkzZDsKICAgICAgLS1kYW5nZXI6ICNlZjQ0NDQ7CiAgICB9CiAgICAqIHsKICAgICAgYm94LXNpemluZzogYm9yZGVyLWJveDsKICAgICAgbWFyZ2luOiAwOwogICAgICBwYWRkaW5nOiAwOwogICAgICBmb250LWZhbWlseTogLWFwcGxlLXN5c3RlbSwgQmxpbmtNYWNTeXN0ZW1Gb250LCAiU2Vnb2UgVUkiLCBSb2JvdG8sIE94eWdlbiwgVWJ1bnR1LCBDYW50YXJlbGwsIHNhbnMtc2VyaWY7CiAgICB9CiAgICBib2R5IHsKICAgICAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tYmcpOwogICAgICBjb2xvcjogdmFyKC0tdGV4dCk7CiAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47CiAgICAgIGhlaWdodDogMTAwdmg7CiAgICAgIGhlaWdodDogMTAwZHZoOwogICAgICBvdmVyZmxvdzogaGlkZGVuOwogICAgfQogICAgLyogTWluaW1hbCBDZW50ZXIgSGVhZGVyICovCiAgICBoZWFkZXIgewogICAgICBwYWRkaW5nOiAxNnB4IDIwcHg7CiAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyOwogICAgICBwb3NpdGlvbjogcmVsYXRpdmU7CiAgICAgIGJvcmRlci1ib3R0b206IDFweCBzb2xpZCB2YXIoLS1ib3JkZXIpOwogICAgICBiYWNrZ3JvdW5kOiByZ2JhKDExLCAxNSwgMjUsIDAuODUpOwogICAgICBiYWNrZHJvcC1maWx0ZXI6IGJsdXIoMTJweCk7CiAgICAgIGZsZXgtc2hyaW5rOiAwOwogICAgfQogICAgLmJyYW5kIHsKICAgICAgZm9udC1zaXplOiAyMnB4OwogICAgICBmb250LXdlaWdodDogODAwOwogICAgICBsZXR0ZXItc3BhY2luZzogNHB4OwogICAgICBjb2xvcjogdmFyKC0tdGV4dCk7CiAgICAgIHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7CiAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgICAgIGdhcDogMTBweDsKICAgIH0KICAgIC5zdGF0dXMtZG90IHsKICAgICAgd2lkdGg6IDhweDsKICAgICAgaGVpZ2h0OiA4cHg7CiAgICAgIGJvcmRlci1yYWRpdXM6IDUwJTsKICAgICAgYmFja2dyb3VuZDogIzEwYjk4MTsKICAgICAgYm94LXNoYWRvdzogMCAwIDEwcHggIzEwYjk4MTsKICAgICAgYW5pbWF0aW9uOiBwdWxzZSAyLjVzIGluZmluaXRlOwogICAgfQogICAgQGtleWZyYW1lcyBwdWxzZSB7CiAgICAgIDAlLCAxMDAlIHsgb3BhY2l0eTogMTsgdHJhbnNmb3JtOiBzY2FsZSgxKTsgfQogICAgICA1MCUgeyBvcGFjaXR5OiAwLjU7IHRyYW5zZm9ybTogc2NhbGUoMC44NSk7IH0KICAgIH0KICAgIC8qIENoYXQgQ29udGFpbmVyICovCiAgICAjY2hhdC1jb250YWluZXIgewogICAgICBmbGV4OiAxOwogICAgICBvdmVyZmxvdy15OiBhdXRvOwogICAgICBwYWRkaW5nOiAyNHB4IDIwcHg7CiAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47CiAgICAgIGdhcDogMThweDsKICAgICAgbWF4LXdpZHRoOiA4NDBweDsKICAgICAgd2lkdGg6IDEwMCU7CiAgICAgIG1hcmdpbjogMCBhdXRvOwogICAgICBzY3JvbGwtYmVoYXZpb3I6IHNtb290aDsKICAgIH0KICAgIC5tc2cgewogICAgICBkaXNwbGF5OiBmbGV4OwogICAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uOwogICAgICBtYXgtd2lkdGg6IDgyJTsKICAgICAgYW5pbWF0aW9uOiBmYWRlSW4gMC4ycyBjdWJpYy1iZXppZXIoMC4xNiwgMSwgMC4zLCAxKTsKICAgIH0KICAgIEBrZXlmcmFtZXMgZmFkZUluIHsKICAgICAgZnJvbSB7IG9wYWNpdHk6IDA7IHRyYW5zZm9ybTogdHJhbnNsYXRlWSg4cHgpOyB9CiAgICAgIHRvIHsgb3BhY2l0eTogMTsgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKDApOyB9CiAgICB9CiAgICAubXNnLnVzZXIgewogICAgICBhbGlnbi1zZWxmOiBmbGV4LWVuZDsKICAgIH0KICAgIC5tc2cudXNlciAuYnViYmxlIHsKICAgICAgYmFja2dyb3VuZDogdmFyKC0tYnViYmxlLXVzZXIpOwogICAgICBjb2xvcjogI2ZmZmZmZjsKICAgICAgYm9yZGVyLXJhZGl1czogMThweCAxOHB4IDRweCAxOHB4OwogICAgICBib3gtc2hhZG93OiAwIDRweCAxNnB4IHJnYmEoMzcsIDk5LCAyMzUsIDAuMjUpOwogICAgfQogICAgLm1zZy50YXJhIHsKICAgICAgYWxpZ24tc2VsZjogZmxleC1zdGFydDsKICAgIH0KICAgIC5tc2cudGFyYSAuYnViYmxlIHsKICAgICAgYmFja2dyb3VuZDogdmFyKC0tYnViYmxlLXRhcmEpOwogICAgICBjb2xvcjogdmFyKC0tdGV4dCk7CiAgICAgIGJvcmRlci1yYWRpdXM6IDE4cHggMThweCAxOHB4IDRweDsKICAgICAgYm9yZGVyOiAxcHggc29saWQgdmFyKC0tYm9yZGVyKTsKICAgICAgYm94LXNoYWRvdzogMCA0cHggMTZweCByZ2JhKDAsIDAsIDAsIDAuMik7CiAgICB9CiAgICAuYnViYmxlIHsKICAgICAgcGFkZGluZzogMTRweCAyMHB4OwogICAgICBmb250LXNpemU6IDE1cHg7CiAgICAgIGxpbmUtaGVpZ2h0OiAxLjY7CiAgICAgIHdvcmQtYnJlYWs6IGJyZWFrLXdvcmQ7CiAgICAgIHdoaXRlLXNwYWNlOiBwcmUtd3JhcDsKICAgIH0KICAgIC8qIEZvb3RlciAmIElucHV0IEJveCAqLwogICAgZm9vdGVyIHsKICAgICAgcGFkZGluZzogMTZweCAyMHB4IDIwcHg7CiAgICAgIGJhY2tncm91bmQ6IHJnYmEoMTEsIDE1LCAyNSwgMC45NSk7CiAgICAgIGJhY2tkcm9wLWZpbHRlcjogYmx1cigxMnB4KTsKICAgICAgYm9yZGVyLXRvcDogMXB4IHNvbGlkIHZhcigtLWJvcmRlcik7CiAgICAgIGZsZXgtc2hyaW5rOiAwOwogICAgfQogICAgLmlucHV0LWJveCB7CiAgICAgIG1heC13aWR0aDogODQwcHg7CiAgICAgIG1hcmdpbjogMCBhdXRvOwogICAgICBkaXNwbGF5OiBmbGV4OwogICAgICBhbGlnbi1pdGVtczogY2VudGVyOwogICAgICBnYXA6IDEwcHg7CiAgICAgIGJhY2tncm91bmQ6IHZhcigtLWNhcmQtYmcpOwogICAgICBib3JkZXI6IDFweCBzb2xpZCB2YXIoLS1ib3JkZXIpOwogICAgICBib3JkZXItcmFkaXVzOiAyOHB4OwogICAgICBwYWRkaW5nOiA2cHggOHB4IDZweCAxOHB4OwogICAgICB0cmFuc2l0aW9uOiBhbGwgMC4ycyBlYXNlOwogICAgICBib3gtc2hhZG93OiAwIDRweCAyMHB4IHJnYmEoMCwgMCwgMCwgMC4zKTsKICAgIH0KICAgIC5pbnB1dC1ib3g6Zm9jdXMtd2l0aGluIHsKICAgICAgYm9yZGVyLWNvbG9yOiB2YXIoLS1hY2NlbnQpOwogICAgICBib3gtc2hhZG93OiAwIDAgMCAzcHggdmFyKC0tYWNjZW50LWdsb3cpOwogICAgfQogICAgI2NoYXQtaW5wdXQgewogICAgICBmbGV4OiAxOwogICAgICBiYWNrZ3JvdW5kOiB0cmFuc3BhcmVudDsKICAgICAgYm9yZGVyOiBub25lOwogICAgICBjb2xvcjogdmFyKC0tdGV4dCk7CiAgICAgIGZvbnQtc2l6ZTogMTVweDsKICAgICAgb3V0bGluZTogbm9uZTsKICAgICAgcGFkZGluZzogOHB4IDA7CiAgICB9CiAgICAjY2hhdC1pbnB1dDo6cGxhY2Vob2xkZXIgewogICAgICBjb2xvcjogdmFyKC0tdGV4dC1tdXRlZCk7CiAgICB9CiAgICAvKiBWb2ljZSBNaWMgQnV0dG9uICovCiAgICAuYnRuLW1pYyB7CiAgICAgIGJhY2tncm91bmQ6IHRyYW5zcGFyZW50OwogICAgICBib3JkZXI6IG5vbmU7CiAgICAgIGNvbG9yOiB2YXIoLS10ZXh0LW11dGVkKTsKICAgICAgd2lkdGg6IDQwcHg7CiAgICAgIGhlaWdodDogNDBweDsKICAgICAgYm9yZGVyLXJhZGl1czogNTAlOwogICAgICBkaXNwbGF5OiBmbGV4OwogICAgICBhbGlnbi1pdGVtczogY2VudGVyOwogICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjsKICAgICAgY3Vyc29yOiBwb2ludGVyOwogICAgICBmb250LXNpemU6IDE5cHg7CiAgICAgIHRyYW5zaXRpb246IGFsbCAwLjJzIGVhc2U7CiAgICAgIGZsZXgtc2hyaW5rOiAwOwogICAgfQogICAgLmJ0bi1taWM6aG92ZXIgewogICAgICBjb2xvcjogdmFyKC0tYWNjZW50KTsKICAgICAgYmFja2dyb3VuZDogcmdiYSg1NiwgMTg5LCAyNDgsIDAuMSk7CiAgICB9CiAgICAuYnRuLW1pYy5hY3RpdmUgewogICAgICBjb2xvcjogI2ZmZmZmZjsKICAgICAgYmFja2dyb3VuZDogdmFyKC0tZGFuZ2VyKTsKICAgICAgYm94LXNoYWRvdzogMCAwIDE0cHggcmdiYSgyMzksIDY4LCA2OCwgMC43KTsKICAgICAgYW5pbWF0aW9uOiBwdWxzZU1pYyAxLjJzIGluZmluaXRlOwogICAgfQogICAgQGtleWZyYW1lcyBwdWxzZU1pYyB7CiAgICAgIDAlIHsgdHJhbnNmb3JtOiBzY2FsZSgxKTsgfQogICAgICA1MCUgeyB0cmFuc2Zvcm06IHNjYWxlKDEuMSk7IH0KICAgICAgMTAwJSB7IHRyYW5zZm9ybTogc2NhbGUoMSk7IH0KICAgIH0KICAgIC8qIFNlbmQgQnV0dG9uICovCiAgICAjYnRuLXNlbmQgewogICAgICBiYWNrZ3JvdW5kOiB2YXIoLS1hY2NlbnQpOwogICAgICBjb2xvcjogIzBiMGYxOTsKICAgICAgYm9yZGVyOiBub25lOwogICAgICB3aWR0aDogNDBweDsKICAgICAgaGVpZ2h0OiA0MHB4OwogICAgICBib3JkZXItcmFkaXVzOiA1MCU7CiAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyOwogICAgICBjdXJzb3I6IHBvaW50ZXI7CiAgICAgIGZvbnQtc2l6ZTogMTZweDsKICAgICAgZm9udC13ZWlnaHQ6IDcwMDsKICAgICAgdHJhbnNpdGlvbjogYWxsIDAuMnMgZWFzZTsKICAgICAgZmxleC1zaHJpbms6IDA7CiAgICB9CiAgICAjYnRuLXNlbmQ6aG92ZXIgewogICAgICBiYWNrZ3JvdW5kOiAjN2RkM2ZjOwogICAgICB0cmFuc2Zvcm06IHNjYWxlKDEuMDUpOwogICAgfQogICAgI2J0bi1zZW5kOmRpc2FibGVkIHsKICAgICAgb3BhY2l0eTogMC40OwogICAgICBjdXJzb3I6IG5vdC1hbGxvd2VkOwogICAgICB0cmFuc2Zvcm06IG5vbmU7CiAgICB9CiAgICBAbWVkaWEgKG1heC13aWR0aDogNjQwcHgpIHsKICAgICAgLmJyYW5kIHsgZm9udC1zaXplOiAxOXB4OyB9CiAgICAgIC5idWJibGUgeyBmb250LXNpemU6IDE0cHg7IHBhZGRpbmc6IDEycHggMTZweDsgfQogICAgICAjY2hhdC1jb250YWluZXIgeyBwYWRkaW5nOiAxNnB4IDEycHg7IH0KICAgICAgZm9vdGVyIHsgcGFkZGluZzogMTJweCAxMnB4IDE2cHg7IH0KICAgIH0KICA8L3N0eWxlPgo8L2hlYWQ+Cjxib2R5PgoKICA8aGVhZGVyPgogICAgPGRpdiBjbGFzcz0iYnJhbmQiPgogICAgICA8c3BhbiBjbGFzcz0ic3RhdHVzLWRvdCI+PC9zcGFuPgogICAgICBUQVJBCiAgICA8L2Rpdj4KICA8L2hlYWRlcj4KCiAgPGRpdiBpZD0iY2hhdC1jb250YWluZXIiPgogICAgPGRpdiBjbGFzcz0ibXNnIHRhcmEiPgogICAgICA8ZGl2IGNsYXNzPSJidWJibGUiPkhlbGxvLiBJIGFtIFRBUkEuIEhvdyBtYXkgSSBhc3Npc3QgeW91IHRvZGF5PzwvZGl2PgogICAgPC9kaXY+CiAgPC9kaXY+CgogIDxmb290ZXI+CiAgICA8Zm9ybSBjbGFzcz0iaW5wdXQtYm94IiBvbnN1Ym1pdD0iaGFuZGxlU2VuZChldmVudCkiPgogICAgICA8aW5wdXQgdHlwZT0idGV4dCIgaWQ9ImNoYXQtaW5wdXQiIHBsYWNlaG9sZGVyPSJNZXNzYWdlIFRBUkEuLi4iIGF1dG9jb21wbGV0ZT0ib2ZmIiAvPgogICAgICA8YnV0dG9uIHR5cGU9ImJ1dHRvbiIgaWQ9ImJ0bi1taWMiIGNsYXNzPSJidG4tbWljIiBvbmNsaWNrPSJ0b2dnbGVWb2ljZSgpIiB0aXRsZT0iVm9pY2UgaW5wdXQiPvCfjpnvuI88L2J1dHRvbj4KICAgICAgPGJ1dHRvbiB0eXBlPSJzdWJtaXQiIGlkPSJidG4tc2VuZCI+4p6UPC9idXR0b24+CiAgICA8L2Zvcm0+CiAgPC9mb290ZXI+CgogIDxzY3JpcHQ+CiAgICBjb25zdCBjaGF0Q29udGFpbmVyID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoImNoYXQtY29udGFpbmVyIik7CiAgICBjb25zdCBjaGF0SW5wdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgiY2hhdC1pbnB1dCIpOwogICAgY29uc3Qgc2VuZEJ0biA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJidG4tc2VuZCIpOwogICAgY29uc3QgbWljQnRuID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoImJ0bi1taWMiKTsKCiAgICBmdW5jdGlvbiBhcHBlbmRNZXNzYWdlKHNlbmRlciwgdGV4dCkgewogICAgICBjb25zdCBtc2dEaXYgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCJkaXYiKTsKICAgICAgbXNnRGl2LmNsYXNzTmFtZSA9IGBtc2cgJHtzZW5kZXJ9YDsKICAgICAgY29uc3QgYnViYmxlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgiZGl2Iik7CiAgICAgIGJ1YmJsZS5jbGFzc05hbWUgPSAiYnViYmxlIjsKICAgICAgYnViYmxlLnRleHRDb250ZW50ID0gdGV4dDsKICAgICAgbXNnRGl2LmFwcGVuZENoaWxkKGJ1YmJsZSk7CiAgICAgIGNoYXRDb250YWluZXIuYXBwZW5kQ2hpbGQobXNnRGl2KTsKICAgICAgY2hhdENvbnRhaW5lci5zY3JvbGxUb3AgPSBjaGF0Q29udGFpbmVyLnNjcm9sbEhlaWdodDsKICAgICAgcmV0dXJuIGJ1YmJsZTsKICAgIH0KCiAgICBhc3luYyBmdW5jdGlvbiBzZW5kQ2hhdFJlcXVlc3QocHJvbXB0VGV4dCkgewogICAgICBjb25zdCBlbmRwb2ludHMgPSBbXTsKICAgICAgY29uc3Qgb3JpZ2luID0gd2luZG93LmxvY2F0aW9uLm9yaWdpbjsKCiAgICAgIC8vIDEuIFByaW9yaXRpemUgcmVsYXRpdmUgcHJvZHVjdGlvbiBjaGF0IGVuZHBvaW50CiAgICAgIGlmIChvcmlnaW4gJiYgb3JpZ2luICE9PSAibnVsbCIgJiYgIW9yaWdpbi5zdGFydHNXaXRoKCJmaWxlOiIpKSB7CiAgICAgICAgZW5kcG9pbnRzLnB1c2goYCR7b3JpZ2lufS92MS9jaGF0YCk7CiAgICAgICAgZW5kcG9pbnRzLnB1c2goYCR7b3JpZ2lufS9hcGkvdjEvY2hhdGApOwogICAgICB9CgogICAgICAvLyAyLiBEaXJlY3QgbGl2ZSBIdWdnaW5nIEZhY2UgcHJvZHVjdGlvbiBiYWNrZW5kCiAgICAgIGVuZHBvaW50cy5wdXNoKCJodHRwczovL21hbmp1a3A2LXRhcmEuaGYuc3BhY2UvdjEvY2hhdCIpOwogICAgICBlbmRwb2ludHMucHVzaCgiaHR0cHM6Ly9tYW5qdWtwNi10YXJhLmhmLnNwYWNlL2FwaS92MS9jaGF0Iik7CgogICAgICAvLyAzLiBMb2NhbGhvc3QgZW5kcG9pbnRzIGZvciBsb2NhbCB0ZXN0aW5nCiAgICAgIGVuZHBvaW50cy5wdXNoKCJodHRwOi8vMTI3LjAuMC4xOjc4NjAvdjEvY2hhdCIpOwogICAgICBlbmRwb2ludHMucHVzaCgiaHR0cDovLzEyNy4wLjAuMTo4MDAwL2FwaS92MS9jaGF0Iik7CgogICAgICBjb25zdCBwYXlsb2FkID0gewogICAgICAgIG1lc3NhZ2U6IHByb21wdFRleHQsCiAgICAgICAgcHJvbXB0OiBwcm9tcHRUZXh0LAogICAgICAgIGlucHV0OiBwcm9tcHRUZXh0CiAgICAgIH07CgogICAgICBsZXQgbGFzdEVycm9yID0gbnVsbDsKCiAgICAgIGZvciAoY29uc3QgdXJsIG9mIGVuZHBvaW50cykgewogICAgICAgIHRyeSB7CiAgICAgICAgICBjb25zdCBjb250cm9sbGVyID0gbmV3IEFib3J0Q29udHJvbGxlcigpOwogICAgICAgICAgY29uc3QgdGltZXIgPSBzZXRUaW1lb3V0KCgpID0+IGNvbnRyb2xsZXIuYWJvcnQoKSwgMTIwMDApOwogICAgICAgICAgY29uc3QgcmVzID0gYXdhaXQgZmV0Y2godXJsLCB7CiAgICAgICAgICAgIG1ldGhvZDogIlBPU1QiLAogICAgICAgICAgICBoZWFkZXJzOiB7ICJDb250ZW50LVR5cGUiOiAiYXBwbGljYXRpb24vanNvbiIgfSwKICAgICAgICAgICAgYm9keTogSlNPTi5zdHJpbmdpZnkocGF5bG9hZCksCiAgICAgICAgICAgIHNpZ25hbDogY29udHJvbGxlci5zaWduYWwKICAgICAgICAgIH0pOwogICAgICAgICAgY2xlYXJUaW1lb3V0KHRpbWVyKTsKCiAgICAgICAgICBpZiAocmVzLm9rKSB7CiAgICAgICAgICAgIGNvbnN0IGRhdGEgPSBhd2FpdCByZXMuanNvbigpOwogICAgICAgICAgICByZXR1cm4gKGRhdGEucmVzcG9uc2UgfHwgKGRhdGEuZGF0YSAmJiBkYXRhLmRhdGEucmVzcG9uc2UpIHx8IGRhdGEudGV4dCB8fCBKU09OLnN0cmluZ2lmeShkYXRhKSk7CiAgICAgICAgICB9IGVsc2UgewogICAgICAgICAgICBjb25zdCBlcnJEYXRhID0gYXdhaXQgcmVzLmpzb24oKS5jYXRjaCgoKSA9PiAoe30pKTsKICAgICAgICAgICAgbGFzdEVycm9yID0gbmV3IEVycm9yKGBTZXJ2ZXIgcmV0dXJuZWQgSFRUUCAke3Jlcy5zdGF0dXN9OiAke2VyckRhdGEuZXJyb3IgfHwgZXJyRGF0YS5kZXRhaWwgfHwgIkVycm9yIn1gKTsKICAgICAgICAgIH0KICAgICAgICB9IGNhdGNoIChlKSB7CiAgICAgICAgICBsYXN0RXJyb3IgPSBlOwogICAgICAgIH0KICAgICAgfQoKICAgICAgdGhyb3cgbmV3IEVycm9yKGBSZWFsIFRBUkEgcnVudGltZSB1bnJlYWNoYWJsZTogJHtsYXN0RXJyb3IgPyBsYXN0RXJyb3IubWVzc2FnZSA6ICJTZXJ2aWNlIFVuYXZhaWxhYmxlIn1gKTsKICAgIH0KCiAgICBhc3luYyBmdW5jdGlvbiBoYW5kbGVTZW5kKGUpIHsKICAgICAgaWYgKGUpIGUucHJldmVudERlZmF1bHQoKTsKICAgICAgY29uc3QgdGV4dCA9IGNoYXRJbnB1dC52YWx1ZS50cmltKCk7CiAgICAgIGlmICghdGV4dCkgcmV0dXJuOwoKICAgICAgYXBwZW5kTWVzc2FnZSgidXNlciIsIHRleHQpOwogICAgICBjaGF0SW5wdXQudmFsdWUgPSAiIjsKICAgICAgc2VuZEJ0bi5kaXNhYmxlZCA9IHRydWU7CgogICAgICB0cnkgewogICAgICAgIGNvbnN0IHJlc3BvbnNlID0gYXdhaXQgc2VuZENoYXRSZXF1ZXN0KHRleHQpOwogICAgICAgIGFwcGVuZE1lc3NhZ2UoInRhcmEiLCByZXNwb25zZSk7CiAgICAgICAgc3BlYWtJZkVuYWJsZWQocmVzcG9uc2UpOwogICAgICB9IGNhdGNoIChlcnIpIHsKICAgICAgICBhcHBlbmRNZXNzYWdlKCJ0YXJhIiwgYFtUQVJBIFJ1bnRpbWUgTm90aWNlXTogJHtlcnIubWVzc2FnZX1gKTsKICAgICAgfSBmaW5hbGx5IHsKICAgICAgICBzZW5kQnRuLmRpc2FibGVkID0gZmFsc2U7CiAgICAgICAgY2hhdElucHV0LmZvY3VzKCk7CiAgICAgIH0KICAgIH0KCiAgICAvLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCiAgICAvLyBWb2ljZSBFbmdpbmUgKFNwZWVjaC10by1UZXh0ICYgVGV4dC10by1TcGVlY2gpCiAgICAvLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCiAgICBsZXQgcmVjb2duaXRpb24gPSBudWxsOwogICAgbGV0IGlzTGlzdGVuaW5nID0gZmFsc2U7CiAgICBsZXQgdm9pY2VBY3RpdmUgPSBmYWxzZTsKCiAgICBmdW5jdGlvbiBpbml0Vm9pY2UoKSB7CiAgICAgIGNvbnN0IFNwZWVjaFJlY29nbml0aW9uID0gd2luZG93LlNwZWVjaFJlY29nbml0aW9uIHx8IHdpbmRvdy53ZWJraXRTcGVlY2hSZWNvZ25pdGlvbjsKICAgICAgaWYgKCFTcGVlY2hSZWNvZ25pdGlvbikgcmV0dXJuOwoKICAgICAgdHJ5IHsKICAgICAgICByZWNvZ25pdGlvbiA9IG5ldyBTcGVlY2hSZWNvZ25pdGlvbigpOwogICAgICAgIHJlY29nbml0aW9uLmNvbnRpbnVvdXMgPSBmYWxzZTsKICAgICAgICByZWNvZ25pdGlvbi5pbnRlcmltUmVzdWx0cyA9IGZhbHNlOwogICAgICAgIHJlY29nbml0aW9uLmxhbmcgPSAiZW4tVVMiOwoKICAgICAgICByZWNvZ25pdGlvbi5vbnN0YXJ0ID0gKCkgPT4gewogICAgICAgICAgaXNMaXN0ZW5pbmcgPSB0cnVlOwogICAgICAgICAgbWljQnRuLmNsYXNzTGlzdC5hZGQoImFjdGl2ZSIpOwogICAgICAgIH07CgogICAgICAgIHJlY29nbml0aW9uLm9ucmVzdWx0ID0gKGV2ZW50KSA9PiB7CiAgICAgICAgICBjb25zdCB0cmFuc2NyaXB0ID0gZXZlbnQucmVzdWx0c1swXVswXS50cmFuc2NyaXB0OwogICAgICAgICAgY2hhdElucHV0LnZhbHVlID0gdHJhbnNjcmlwdDsKICAgICAgICAgIGhhbmRsZVNlbmQoKTsKICAgICAgICB9OwoKICAgICAgICByZWNvZ25pdGlvbi5vbmVycm9yID0gKCkgPT4gewogICAgICAgICAgaXNMaXN0ZW5pbmcgPSBmYWxzZTsKICAgICAgICAgIG1pY0J0bi5jbGFzc0xpc3QucmVtb3ZlKCJhY3RpdmUiKTsKICAgICAgICB9OwoKICAgICAgICByZWNvZ25pdGlvbi5vbmVuZCA9ICgpID0+IHsKICAgICAgICAgIGlzTGlzdGVuaW5nID0gZmFsc2U7CiAgICAgICAgICBtaWNCdG4uY2xhc3NMaXN0LnJlbW92ZSgiYWN0aXZlIik7CiAgICAgICAgfTsKICAgICAgfSBjYXRjaCAoZSkgewogICAgICAgIGNvbnNvbGUud2FybigiVm9pY2UgaW5pdDoiLCBlKTsKICAgICAgfQogICAgfQoKICAgIGZ1bmN0aW9uIHRvZ2dsZVZvaWNlKCkgewogICAgICBpZiAoIXJlY29nbml0aW9uKSB7CiAgICAgICAgaW5pdFZvaWNlKCk7CiAgICAgIH0KICAgICAgaWYgKCFyZWNvZ25pdGlvbikgewogICAgICAgIGFsZXJ0KCJTcGVlY2ggcmVjb2duaXRpb24gaXMgbm90IHN1cHBvcnRlZCBpbiB0aGlzIGJyb3dzZXIuIik7CiAgICAgICAgcmV0dXJuOwogICAgICB9CiAgICAgIHZvaWNlQWN0aXZlID0gdHJ1ZTsKICAgICAgaWYgKGlzTGlzdGVuaW5nKSB7CiAgICAgICAgcmVjb2duaXRpb24uc3RvcCgpOwogICAgICB9IGVsc2UgewogICAgICAgIHRyeSB7CiAgICAgICAgICByZWNvZ25pdGlvbi5zdGFydCgpOwogICAgICAgIH0gY2F0Y2ggKGUpIHsKICAgICAgICAgIHJlY29nbml0aW9uLnN0b3AoKTsKICAgICAgICB9CiAgICAgIH0KICAgIH0KCiAgICBmdW5jdGlvbiBzcGVha0lmRW5hYmxlZCh0ZXh0KSB7CiAgICAgIGlmICghdm9pY2VBY3RpdmUgfHwgIXdpbmRvdy5zcGVlY2hTeW50aGVzaXMpIHJldHVybjsKICAgICAgdHJ5IHsKICAgICAgICB3aW5kb3cuc3BlZWNoU3ludGhlc2lzLmNhbmNlbCgpOwogICAgICAgIGNvbnN0IHV0dGVyYW5jZSA9IG5ldyBTcGVlY2hTeW50aGVzaXNVdHRlcmFuY2UodGV4dCk7CiAgICAgICAgdXR0ZXJhbmNlLnJhdGUgPSAxLjA7CiAgICAgICAgdXR0ZXJhbmNlLnBpdGNoID0gMS4wOwogICAgICAgIHdpbmRvdy5zcGVlY2hTeW50aGVzaXMuc3BlYWsodXR0ZXJhbmNlKTsKICAgICAgfSBjYXRjaCAoZSkge30KICAgIH0KCiAgICBpbml0Vm9pY2UoKTsKICA8L3NjcmlwdD4KPC9ib2R5Pgo8L2h0bWw+Cg==";

function getCanonicalFrontendHTML() {
  const binString = atob(CANONICAL_FRONTEND_B64);
  const bytes = Uint8Array.from(binString, (m) => m.codePointAt(0));
  return new TextDecoder().decode(bytes);
}

function handleChatUI(env) {
  const html = getCanonicalFrontendHTML();
  return new Response(html, {
    headers: { "Content-Type": "text/html;charset=UTF-8", ...CORS_HEADERS }
  });
}

function jsonResponse(obj, status = 200) {
  return new Response(JSON.stringify(obj, null, 2), {
    status,
    headers: { "Content-Type": "application/json;charset=UTF-8", ...CORS_HEADERS }
  });
}

function errorResponse(message, status = 400) {
  return jsonResponse({ error: message, status: "ERROR" }, status);
}
